[build.env]
passthrough = [
    "krb5_cv_attr_constructor_destructor=yes",
    "ac_cv_func_regcomp=yes",
    "ac_cv_printf_positional=yes",
]

[build]
pre-build = ["apt-get update -q && apt-get -yqq install libsasl2-dev"]
