name: Docker consumer
on:
  workflow_run:
    workflows: ["Docker build"]  # Must match the name exactly
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test-load:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"
      - name: Restore binary
        uses: actions/download-artifact@v4
        with:
          name: iceberg-catalog-image
          path: artifacts
          run-id: ${{ github.event.workflow_run.id }}
      - name: Display structure of downloaded files
        run: ls -Rlh artifacts

      - name: Restore Docker image
        run:  docker load -i artifacts/iceberg-catalog-amd64.tar &&  kind load docker-image localhost/iceberg-catalog-local:amd64
