name: integration tests

on:
  workflow_run:
    workflows: ["Docker build"]  # Must match the name exactly
    types:
      - completed


env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        names: [ openfga, pyiceberg, spark_adls, spark_aws_remote_signing, spark_aws_sts, spark_gcs, spark_minio_sts, spark_minio_remote_signing, starrocks, trino ]
    uses: ./.github/workflows/integration_test_workflow.yml
    with:
        test_name: ${{ matrix.names }}
        docker_build_id: ${{ github.event.workflow_run.id }}
    secrets: inherit